"""Synthesis-stage support (M7.3): evidence grounding and checking.

The report is generated by the model, but shipping it is gated by a
deterministic groundedness check outside the LLM path (PLAN M7.3): every
number appearing in the report text must match some numeric value in the
evidence result sets. A violation means the report is not grounded in
executed queries — the run fails and the report is never returned (never
ship a fabricated report).

Strictness notes (deliberate, mirroring the M6 judges' type-strictness):

* Only numeric cells ground numbers. Booleans are excluded (they are a
  separate type in the judges), and string cells — including ISO-8601
  timestamps — are never scanned for digits, so a report cannot ground a
  number in something that merely *contains* digits.
* US number formatting is assumed when parsing the report ("1,234.56");
  thousands separators are stripped before comparison.
* Numbers already present in the task context (the management request and
  the sub-questions) are inputs, not claims: the manager supplied them, so a
  report echoing a time window ("2018"), threshold or identifier is not
  fabricating a measurement and needs no evidence existence proof.
"""

import json
import re
from decimal import Decimal

from app.manager.evidence import EvidenceRecord

# Numbers in prose: optional sign, digits with optional thousands separators
# and decimals — not preceded by a word character or dot, so "R2D2", "v1.2"
# or dotted version strings do not produce phantom numbers.
_NUMBER = re.compile(r"(?<![\w.])-?\d[\d,]*(?:\.\d+)?")

# Groundedness matching tolerance (prose vs. the M6 result-set judges).
#
# Why this is NOT the M6 1e-6 relative tolerance: the M6 judges compare
# *result sets* — both sides are produced by SQL, so near-exactness is
# expected and meaningful. Prose grounding is a different problem: the
# synthesis model quotes numbers in natural language and, despite the
# prompt's "no rounding" instruction, small local models still round
# ("about 250,000" for 249,485.85, "~1,002,560" for 1,002,560.03).
# Applying the 1e-6 rule to prose turned every rounded claim into a false
# positive and hid the only signal that matters: is the number traceable
# to a real row at all? (The 250,000 in the M7.5 manual run — absent from
# every result set — is exactly what must still be rejected.)
#
# The calibrated rule: a report number matches an evidence value when it is
# within 0.5% relative *or* within a +/-10 absolute floor, AND has the
# same sign (a positive claim never matches "negative evidence", e.g.
# "+3.5" is not "-3.5"). Rationale:
#   * 0.5% relative accepts proportional rounding at any magnitude
#     (|250,000 - 249,485.85| = 514 <= 0.5% of 249,485.85 = 1,247).
#   * The +/-10 absolute floor stops *small* values (10.5, 0.06) from
#     being held to exactness — prose says "about 10", not "10.50".
#   * Anything far from every real row value still fails (999.99 vs 10.5),
#     so a fabricated figure is still rejected — the whole point of the
#     guardrail.
#   * The same-sign guard is the deliberate price of the wide floor:
#     without it the +/-10 window would let a sign flip (+3.5 vs -3.5)
#     pass as "rounding".
GROUNDEDNESS_RELATIVE_TOLERANCE = 0.005  # 0.5%
GROUNDEDNESS_ABS_TOLERANCE = 10.0  # +/-10, prose-scale absolute floor


def extract_report_numbers(report: str) -> list[float]:
    """Extract the numeric values mentioned in a report text.

    Thousands separators are stripped ("1,234.56" -> 1234.56). Duplicates are
    kept: the groundedness check is existential per extracted number.
    """
    return [float(match.replace(",", "")) for match in _NUMBER.findall(report)]


def collect_evidence_values(evidence: list[EvidenceRecord]) -> list[float]:
    """Collect every numeric cell value from the evidence result sets."""
    values: list[float] = []
    for record in evidence:
        for row in record.rows or []:
            for cell in row.values():
                if isinstance(cell, bool) or not isinstance(cell, int | float | Decimal):
                    continue
                values.append(float(cell))
    return values


def _number_matches(value: float, number: float) -> bool:
    """True when a report ``number`` can be grounded in one evidence ``value``.

    The calibrated prose tolerance (see the constants above for the full
    rationale): same sign required, then within 0.5% relative or the +/-10
    absolute floor.
    """
    if number * value < 0:  # opposite signs never match
        return False
    return abs(number - value) <= max(
        GROUNDEDNESS_RELATIVE_TOLERANCE * abs(value), GROUNDEDNESS_ABS_TOLERANCE
    )


def groundedness_violation(
    report: str, evidence: list[EvidenceRecord], task: str = ""
) -> str | None:
    """Return a violation message if the report is not fully grounded.

    A report without numbers is trivially grounded. Every number extracted
    from the report must match at least one evidence value within the
    calibrated prose tolerance (``_number_matches``) or one number already
    present in the task context — the ``task`` text plus the sub-questions
    of the evidence records. Numbers the manager supplied are inputs, not
    claims: the agent did not derive them, so echoing them in the report is
    not fabrication.
    """
    values = collect_evidence_values(evidence)
    context_text = task + "\n" + "\n".join(record.sub_question for record in evidence)
    values += extract_report_numbers(context_text)
    for number in extract_report_numbers(report):
        if not any(_number_matches(value, number) for value in values):
            return (
                f"Report number {number} does not appear in any evidence result set "
                f"or task context (groundedness violation)."
            )
    return None


def format_evidence(evidence: list[EvidenceRecord]) -> str:
    """Render the evidence records as the synthesis prompt's grounding text."""
    blocks: list[str] = []
    for record in evidence:
        label = (
            f"Follow-up question {record.sub_index}"
            if record.is_follow_up
            else f"Sub-question {record.sub_index}"
        )
        lines = [f"{label}: {record.sub_question}"]
        if record.error:
            lines.append(f"Status: FAILED — {record.error}")
        else:
            lines.append(f"Status: {record.status}")
            lines.append(f"SQL executed: {record.sql}")
            lines.append(f"Result rows: {json.dumps(record.rows or [], default=str)}")
            if record.answer:
                lines.append(f"Analyst answer: {record.answer}")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)
