"""Synthesis-stage support (M7.3): evidence grounding and checking.

The report is generated by the model, but shipping it is gated by a
deterministic groundedness check outside the LLM path (PLAN M7.3): every
number appearing in the report text must match some numeric value in the
evidence result sets (1e-6 relative tolerance, reused from the M6 judges).
A violation means the report is not grounded in executed queries — the run
fails and the report is never returned (never ship a fabricated report).

Strictness notes (deliberate, mirroring the M6 judges' type-strictness):

* Only numeric cells ground numbers. Booleans are excluded (they are a
  separate type in the judges), and string cells — including ISO-8601
  timestamps — are never scanned for digits, so a report cannot ground a
  number in something that merely *contains* digits.
* US number formatting is assumed when parsing the report ("1,234.56");
  thousands separators are stripped before comparison.
"""

import json
import re
from decimal import Decimal

from app.evaluation.judges import RELATIVE_TOLERANCE
from app.manager.evidence import EvidenceRecord

# Numbers in prose: optional sign, digits with optional thousands separators
# and decimals — not preceded by a word character or dot, so "R2D2", "v1.2"
# or dotted version strings do not produce phantom numbers.
_NUMBER = re.compile(r"(?<![\w.])-?\d[\d,]*(?:\.\d+)?")


def extract_report_numbers(report: str) -> list[float]:
    """Extract the numeric values mentioned in a report text.

    Thousands separators are stripped ("1,234.56" -> 1234.56). Duplicates are
    kept: the groundedness check is existential per extracted number.
    """
    return [float(match.replace(",", "")) for match in _NUMBER.findall(report)]


def collect_evidence_values(evidence: list[EvidenceRecord]) -> list[float]:
    """Collect every numeric cell value from the evidence result sets."""
    values: list[float] = []
    for record in evidence:
        for row in record.rows or []:
            for cell in row.values():
                if isinstance(cell, bool) or not isinstance(cell, int | float | Decimal):
                    continue
                values.append(float(cell))
    return values


def groundedness_violation(report: str, evidence: list[EvidenceRecord]) -> str | None:
    """Return a violation message if the report is not fully grounded.

    A report without numbers is trivially grounded. Every number extracted
    from the report must match at least one evidence value within
    ``RELATIVE_TOLERANCE`` (identical semantics to the M6 judges).
    """
    values = collect_evidence_values(evidence)
    for number in extract_report_numbers(report):
        if not any(
            abs(number - value) <= RELATIVE_TOLERANCE * max(1.0, abs(value)) for value in values
        ):
            return (
                f"Report number {number} does not appear in any evidence result set "
                f"(groundedness violation)."
            )
    return None


def format_evidence(evidence: list[EvidenceRecord]) -> str:
    """Render the evidence records as the synthesis prompt's grounding text."""
    blocks: list[str] = []
    for record in evidence:
        lines = [f"Sub-question {record.sub_index}: {record.sub_question}"]
        if record.error:
            lines.append(f"Status: FAILED — {record.error}")
        else:
            lines.append(f"Status: {record.status}")
            lines.append(f"SQL executed: {record.sql}")
            lines.append(f"Result rows: {json.dumps(record.rows or [], default=str)}")
            if record.answer:
                lines.append(f"Analyst answer: {record.answer}")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)
